version: '3'
services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=jdbc:postgresql://192.168.16.1:5432/products
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=admin
    ports:
      - "8080:8080"
      - "5432:5432"
