version: '3'
services:
  myapp:
    image: your-image-name
    environment:
      - DATABASE_URL=jdbc:postgresql://localhost:5432/products
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=admin
    ports:
      - 8080:8080
